version: '3'
services:
  hafenkran-db:
    image: "postgres:12.0"
    container_name: "hafenkran-db"
    environment:
      - POSTGRES_USER=hafenkran
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=hafenkran
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  hafenkran-clusterservice:
    container_name: hafenkran-clusterservice
    build:
      context: .
      dockerfile: Dockerfile.clusterservice
    expose:
      - "8082"
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - hafenkran-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hafenkran-db:5432/hafenkran

volumes:
  db-data: {}

networks:
  backend:
    driver: bridge