server:
  port:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            # Workaround for hibernate error in Spring Boot < 2.2.0.M(1-4)
            # Remove when updating Spring Boot to a later version
            # https://stackoverflow.com/a/52545424
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 1420MB
      max-request-size: 1420MB

experimentsFileUploadLocation:

mockdata: false
mockKubernetesClient: false

jwt:
  secret:

kubernetes:
  deployment:
    defaults:
      ram: 1000
      cpu: 10
      bookedTime: 3600
  defaultLogLines: 500
  debugging: false
  excludedNamespaces:
    - default
    - kube-node-lease
    - kube-public
    - kube-system
    - kubernetes-dashboard

dockerRegistry.username:
dockerRegistry.password:
dockerRegistry.email:
dockerRegistry.authKey: