server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop

experimentsFileUploadLocation: /tmp/hafenkran-clusterservice

mockdata: true
mockKubernetesClient: true

kubernetes:
  deployment:
    defaults:
      ram: 1000
      cpu: 10
      bookedTime: 3600

jwt:
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB
