server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop

experimentsFileUploadLocation: /tmp/hafenkran-clusterservice

mockdata: true

kubernetes:
  deployment:
    defaults:
      ramDefault: 1000
      cpuDefault: 10
      bookedTimeDefault: 3600

jwt:
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB
