server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

experimentsFileUploadLocation: /tmp/hafenkran-clusterservice

dockerHubRepoPath: hafenkran/hafenkran-repo

mockdata: true
mockKubernetesClient: false
mockMetricsServerClient: false

clusterProxy.path: http://localhost:8001

kubernetes:
  deployment:
    defaults:
      ram: 1000
      cpu: 10
      bookedTime: 3600
  defaultLogLines: 500
  debugging: false

jwt:
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB

dockerRegistry.username: hafenkran
dockerRegistry.password: president encode cold
dockerRegistry.email: hafenkran@protonmail.com
dockerRegistry.authKey: aGFmZW5rcmFuOnByZXNpZGVudCBlbmNvZGUgY29sZA==
