server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

experimentsFileUploadLocation: /tmp/hafenkran-clusterservice

mockdata: true

kubernetes:
  deployment:
    defaults:
      ram: 1000
      cpu: 10
      bookedTime: 3600

jwt:
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB
