server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafenkran
    username: hafenkran
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

experimentsFileUploadLocation: /tmp/hafenkran-clusterservice

dockerHubRepoPath: hafenkran/hafenkran-repo
reportingservice.path: http://localhost:8083

mockdata: true
mockKubernetesClient: false

kubernetes:
  deployment:
    defaults:
      ram: 1000
      cpu: 10
      bookedTime: 3600
  defaultLogLines: 500
  debugging: false

jwt:
  secret: MCgCIQCAS7IFlSvaBOPXwSBHo+7+6C4RbkvYj3fgI5+Abe4pRwIDAQAB

dockerClient:
  username: hafenkran
  password: president encode cold
  email: hafenkran@protonmail.com
  certPath: ~/.docker/certs
  configPath: ~/.docker/config.json
  tls: 0
  host: unix:///var/run/docker.sock
  authKey: aGFmZW5rcmFuOnByZXNpZGVudCBlbmNvZGUgY29sZA==